# Generated by Django 6.0.4 on 2026-04-25 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nama paket')),
                ('description', models.TextField(default='-', verbose_name='deskripsi')),
                ('price', models.IntegerField(default=300000, verbose_name='harga')),
                ('duration', models.CharField(default='2 jam', max_length=50, verbose_name='durasi')),
                ('package_type', models.CharField(choices=[('harian', 'Harian'), ('event', 'Event')], default='harian', max_length=10, verbose_name='tipe')),
                ('package_tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=10, verbose_name='tier')),
                ('is_featured', models.BooleanField(default=False, verbose_name='unggulan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paket',
                'ordering': ['package_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Pernikahan'), ('graduation', 'Wisuda'), ('birthday', 'Ulang Tahun'), ('corporate', 'Korporat'), ('daily', 'Foto Harian'), ('other', 'Lainnya')], default='other', max_length=20, verbose_name='jenis acara')),
                ('event_date', models.DateField(verbose_name='tanggal acara')),
                ('location', models.CharField(max_length=200, verbose_name='lokasi')),
                ('notes', models.TextField(blank=True, default='', verbose_name='catatan tambahan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Dikonfirmasi'), ('in_progress', 'Sedang Berlangsung'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=15, verbose_name='status')),
                ('total_price', models.IntegerField(default=0, verbose_name='total harga')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='klien')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='core.package', verbose_name='paket')),
            ],
            options={
                'verbose_name': 'Pemesanan',
                'verbose_name_plural': 'Pemesanan',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='judul')),
                ('description', models.TextField(blank=True, default='', verbose_name='deskripsi')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL foto')),
                ('file', models.FileField(blank=True, null=True, upload_to='gallery/', verbose_name='file foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='core.booking', verbose_name='pemesanan')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.gallery', verbose_name='album induk')),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='fitur')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='urutan')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.package', verbose_name='paket')),
            ],
            options={
                'verbose_name': 'Fitur Paket',
                'verbose_name_plural': 'Fitur Paket',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', verbose_name='bio')),
                ('specialization', models.CharField(choices=[('wedding', 'Wedding'), ('portrait', 'Portrait'), ('event', 'Event'), ('product', 'Product'), ('landscape', 'Landscape')], default='event', max_length=20, verbose_name='spesialisasi')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='portfolio')),
                ('is_available', models.BooleanField(default=True, verbose_name='tersedia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_profile', to=settings.AUTH_USER_MODEL, verbose_name='akun')),
            ],
            options={
                'verbose_name': 'Fotografer',
                'verbose_name_plural': 'Fotografer',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='photographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.photographer', verbose_name='fotografer'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='rating')),
                ('comment', models.TextField(verbose_name='komentar')),
                ('is_public', models.BooleanField(default=True, verbose_name='tampilkan di publik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.booking', verbose_name='pemesanan')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Review',
                'ordering': ['-created_at'],
            },
        ),
    ]
